# Generated by Django 4.0.5 on 2022-09-12 02:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_Usuario',
            fields=[
                ('id_tipo_usuario', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_tipo_usuario', models.CharField(max_length=100, verbose_name='nombre_tipo_usuario')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100, verbose_name='apellidos')),
                ('documento', models.CharField(max_length=100, verbose_name='documento')),
                ('direccion', models.CharField(max_length=100, verbose_name='direccion')),
                ('telefono', models.CharField(max_length=100, verbose_name='telefono')),
                ('genero', models.CharField(max_length=100, verbose_name='genero')),
                ('fecha_nacimiento', models.CharField(max_length=100, verbose_name='fecha_nacimiento')),
                ('contrasena', models.CharField(max_length=256, verbose_name='contraseña')),
                ('correo', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('username', models.CharField(max_length=150, verbose_name='username')),
                ('fecha_registro', models.CharField(max_length=100, verbose_name='fecha_registro')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('id_tipo_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipo_usuario', to='SHCapp.tipo_usuario')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id_medico', models.IntegerField(primary_key=True, serialize=False)),
                ('especialidad', models.CharField(max_length=100, verbose_name='especialidad')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
