# Generated by Django 4.0.5 on 2022-09-12 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SHCapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='nombre'),
        ),
    ]
