# Generated by Django 4.0.5 on 2022-09-12 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SHCapp', '0002_alter_user_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='nombre'),
        ),
    ]
