# Generated by Django 4.0.5 on 2022-09-12 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SHCapp', '0004_alter_user_apellidos_alter_user_contrasena_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='email'),
        ),
    ]
