# Generated by Django 4.0.5 on 2022-09-12 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SHCapp', '0006_alter_user_id_tipo_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='apellidos',
            field=models.CharField(max_length=100, null=True, verbose_name='apellidos'),
        ),
        migrations.AlterField(
            model_name='user',
            name='contrasena',
            field=models.CharField(max_length=256, null=True, verbose_name='contraseña'),
        ),
        migrations.AlterField(
            model_name='user',
            name='correo',
            field=models.EmailField(max_length=254, null=True, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='direccion',
            field=models.CharField(max_length=100, null=True, verbose_name='direccion'),
        ),
        migrations.AlterField(
            model_name='user',
            name='documento',
            field=models.CharField(max_length=100, null=True, verbose_name='documento'),
        ),
        migrations.AlterField(
            model_name='user',
            name='fecha_nacimiento',
            field=models.CharField(max_length=100, null=True, verbose_name='fecha_nacimiento'),
        ),
        migrations.AlterField(
            model_name='user',
            name='fecha_registro',
            field=models.CharField(max_length=100, null=True, verbose_name='fecha_registro'),
        ),
        migrations.AlterField(
            model_name='user',
            name='genero',
            field=models.CharField(max_length=100, null=True, verbose_name='genero'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id_tipo_usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipo_usuario', to='SHCapp.tipo_usuario'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nombre',
            field=models.CharField(max_length=100, null=True, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, null=True, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telefono',
            field=models.CharField(max_length=100, null=True, verbose_name='telefono'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, null=True, verbose_name='username'),
        ),
    ]
