# Generated by Django 4.0.5 on 2022-09-12 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SHCapp', '0007_alter_user_apellidos_alter_user_contrasena_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id_tipo_usuario',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='tipo_usuario', to='SHCapp.tipo_usuario'),
        ),
    ]
