# Generated by Django 4.1.1 on 2022-09-18 23:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SHCapp', '0010_alter_user_id_tipo_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Medico', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Enfermero',
            fields=[
                ('id_enfermero', models.IntegerField(primary_key=True, serialize=False)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Enfermero', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cuidador',
            fields=[
                ('id_cuidador', models.IntegerField(primary_key=True, serialize=False)),
                ('parentesco', models.CharField(max_length=100, verbose_name='parentesco')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Cuidador', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Auxiliar',
            fields=[
                ('id_auxiliar', models.IntegerField(primary_key=True, serialize=False)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Auxiliar', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AsignacionMedico',
            fields=[
                ('id_asignacion_medico', models.IntegerField(primary_key=True, serialize=False)),
                ('id_medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignacionmed', to=settings.AUTH_USER_MODEL)),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignacionmedico', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AsignacionEnfermero',
            fields=[
                ('id_asignacion_enfermero', models.IntegerField(primary_key=True, serialize=False)),
                ('id_enfermero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignacionenf', to=settings.AUTH_USER_MODEL)),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignacionenfermero', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
