# Generated by Django 4.1.1 on 2022-09-18 23:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SHCapp', '0011_alter_medico_id_usuario_enfermero_cuidador_auxiliar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id_paciente', models.IntegerField(primary_key=True, serialize=False)),
                ('latitud', models.CharField(max_length=100, null=True, verbose_name='latitud')),
                ('longitud', models.CharField(max_length=100, null=True, verbose_name='longitud')),
                ('id_cuidador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CuidadorPaciente', to=settings.AUTH_USER_MODEL)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsarioPaciente', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
